global:
  resolve_timeout: 5m

route:
  receiver: 'default-receiver'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'sre-team@example.com'
        from: 'node1@example.com'
        smarthost: 'mailhog:1025'

inhibit_rules:
  - source_matchers:
      - severity = 'critical'
    target_matchers:
      - severity =~ 'warning|info'
    equal:
      - alertname
      - cluster
      - service
