version: '3.7'

services:
  geth:
    image: ethereum/client-go:stable
<<<<<<< HEAD
    container_name: ethereum-node
    command: ["--syncmode", "full", "--testnet", "--http", "--http.addr", "0.0.0.0", "--http.port", "8545", "--http.api", "eth,net,web3", "--metrics"]
=======
    container_name: geth
    command: [
      "--http", "--http.addr=0.0.0.0", "--http.port=8545", "--http.api=eth,net,web3",
      "--syncmode=full", "--metrics"
    ]
>>>>>>> 24a393dc5ae793be0ad75764dc2659fb0b421623
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./geth/data:/root/.ethereum
    networks:
      - eth-net

  lighthouse:
    image: sigp/lighthouse:latest
    container_name: lighthouse
    command: [
      "--network", "holesky",
      "--execution-endpoint", "http://geth:8545",
      "--http", "--http-address", "0.0.0.0",
      "--metrics"
    ]
    ports:
      - "5052:5052"
    volumes:
      - ./lighthouse/data:/root/.lighthouse
    networks:
      - eth-net
    depends_on:
      - geth

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - eth-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - eth-net
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.8.1
    container_name: loki
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - eth-net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/config.yml
    ports:
      - "9093:9093"
    networks:
      - eth-net

  promtail:
    image: grafana/promtail:2.8.1
    container_name: promtail
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
    networks:
      - eth-net

volumes:
  grafana-data:

networks:
  eth-net:
