{
 "title": "Geth: Multiple",
 "description": "Various metrics of multiple geth instances",
 "tags": [ "geth" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance)(chain_head_header{}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg_over_time(system_cpu_sysload{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(system_cpu_syswait{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(system_memory_used{}[$__interval])) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk read ops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "(irate(system_disk_readcount{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(system_disk_readdata[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk write ops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "(irate(system_disk_writecount{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(system_disk_writedata{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network ingress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(p2p_ingress{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network egress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(p2p_egress{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dials",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "(irate(p2p_dials{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Serves",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "(irate(p2p_serves{}[$__interval])) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(p2p_peers{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Lifetime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(les_connection_duration{quantile=\"0.5\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "LevelDB reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(eth_db_chaindata_disk_read{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "LevelDB writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(eth_db_chaindata_disk_write{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "LevelDB compactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(eth_db_chaindata_compact_time{}[$__interval]))  / 10000000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "LevelDB size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(eth_db_chaindata_disk_size{})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ancient reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(eth_db_chaindata_ancient_read{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ancient writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(irate(eth_db_chaindata_ancient_write{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ancient size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (instance)(eth_db_chaindata_ancient_size{})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Head header",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(chain_head_header{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Head fast block",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(chain_head_receipt{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Head block",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(chain_head_block{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(txpool_pending{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(txpool_queued{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Transaction slots",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(txpool_slots{}[$__interval])) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}